workflows:
  integration-emerge-ios-workflow:
    name: Integration Emerge Tools iOS Workflow
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.sample.emerge
      groups:
        - emerge_credentials # <-- Emerge API Key
      vars:
        XCODE_PROJECT: "emerge.xcodeproj" # <-- Put the name of your project here.
        XCODE_SCHEME: "emerge" # <-- Put the name of your scheme here.
        APP_STORE_APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: false
    scripts:
      - name: Install related Ruby gems
        script: |
          bundle install
      - name: Install Emerge fastlane plugin
        script: |
          fastlane add_plugin emerge
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
      - name: Upload archive to Emerge Tools
        script: |
          bundle exec fastlane emerge_app_upload
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
      email:
        recipients:
          - user1@example.com
          - user2@example.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#builds"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: false # To not receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
