name: flutter_desktop_sample
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.13

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

msix_config:
  display_name: <AppName>
  publisher_display_name: <PublisherName>
  identity_name: <PublisherName.AppName>
  publisher: <PublisherID>
  msix_version: 1.0.0.0
  logo_path: ./logo/flutter-desktop-logo-256x256.png
  store: true
