workflows:
  native-android:
    name: Integrations Katalon Android
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - katalon_credentials
      node: v16.11.1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug
      - name: Test
        script: |
          ./gradlew test
        test_report: app/build/test-results/**/*.xml
      - name: Build Android production release
        script: |
          ./gradlew assembleRelease
      - name: Uploading to Katalon
        script: |
          docker run -t --rm \
            -v $CM_BUILD_DIR/app/build/test-results/testReleaseUnitTest/:/katalon/report \
            -e PASSWORD=$KATALON_API_KEY \
            -e PROJECT_ID=$KATALON_PROJECT_ID \
            -e TYPE=junit \
            -e REPORT_PATH=/katalon/report katalonstudio/report-uploader:0.0.8
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/test-results/**/*.xml
    publishing:
      email:
        recipients:
          - user1@example.com
          - user2@example.com
        notify:
          success: true
          failure: false