plugin 'cocoapods-xcremotecache'

xcremotecache({
    'cache_addresses' => ['https://bucketName.s3.ap-south-1.amazonaws.com/'], 
    'primary_repo' => 'https://linkToTheRepository.git',
    'mode' => 'producer',
    'final_target' => '<Name of Target>',
    'primary_branch' => 'main',
    'aws_secret_key' => '<Secret Access Key>',
    'aws_access_key' => '<Access Key ID>',
    'aws_region' => 'ap-south-1',
    'aws_service' => 's3'
})

target 'XCRemoteCacheExample' do
pod 'SDWebImageSwiftUI'
end
