require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'detoxer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'

  target 'detoxerTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end

target 'detoxer-tvOS' do
  target 'detoxer-tvOSTests' do
    inherit! :search_paths
  end
end