require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'detoxer' do
  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"]
  )

  target 'detoxerTests' do
    inherit! :complete
  end

  # ❌ Removed Flipper completely (fixes build failure on CI/Xcode 26+)

  post_install do |installer|
    # React Native post install
    react_native_post_install(installer)

    # Fix for Xcode 12+ / new toolchains
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end

target 'detoxer-tvOS' do
  target 'detoxer-tvOSTests' do
    inherit! :search_paths
  end
end